package com.prgmtc.keymatrix.vista.per;

public class pnDocente extends javax.swing.JPanel {

    /**
     * Creates new form pnEstudiante
     */
    public pnDocente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblContrato = new javax.swing.JLabel();
        txtContrato = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 102, 102));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(720, 120));
        setLayout(null);

        lblContrato.setBackground(new java.awt.Color(153, 153, 153));
        lblContrato.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblContrato.setForeground(new java.awt.Color(0, 0, 0));
        lblContrato.setText("Contrato");
        add(lblContrato);
        lblContrato.setBounds(70, 40, 140, 30);

        txtContrato.setBackground(new java.awt.Color(255, 255, 255));
        txtContrato.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtContrato.setForeground(new java.awt.Color(0, 0, 0));
        txtContrato.setBorder(null);
        txtContrato.setMinimumSize(new java.awt.Dimension(1, 20));
        txtContrato.setPreferredSize(new java.awt.Dimension(1, 20));
        add(txtContrato);
        txtContrato.setBounds(210, 40, 390, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblContrato;
    private javax.swing.JTextField txtContrato;
    // End of variables declaration//GEN-END:variables
}
