package com.prgmtc.keymatrix.vista.per;

public class pnEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form pnEstudiante
     */
    public pnEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCodigoMarcacion = new javax.swing.JLabel();
        txtCodigoMarcacion = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        txtCargo = new javax.swing.JTextField();

        setBackground(new java.awt.Color(102, 102, 102));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(720, 120));
        setLayout(null);

        lblCodigoMarcacion.setBackground(new java.awt.Color(153, 153, 153));
        lblCodigoMarcacion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblCodigoMarcacion.setForeground(new java.awt.Color(0, 0, 0));
        lblCodigoMarcacion.setText("Cod.");
        add(lblCodigoMarcacion);
        lblCodigoMarcacion.setBounds(70, 40, 50, 30);

        txtCodigoMarcacion.setBackground(new java.awt.Color(255, 255, 255));
        txtCodigoMarcacion.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCodigoMarcacion.setForeground(new java.awt.Color(0, 0, 0));
        txtCodigoMarcacion.setBorder(null);
        txtCodigoMarcacion.setMinimumSize(new java.awt.Dimension(1, 20));
        txtCodigoMarcacion.setPreferredSize(new java.awt.Dimension(1, 20));
        add(txtCodigoMarcacion);
        txtCodigoMarcacion.setBounds(120, 40, 100, 30);

        lblCargo.setBackground(new java.awt.Color(153, 153, 153));
        lblCargo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblCargo.setForeground(new java.awt.Color(0, 0, 0));
        lblCargo.setText("Cargo");
        add(lblCargo);
        lblCargo.setBounds(250, 40, 60, 30);

        txtCargo.setBackground(new java.awt.Color(255, 255, 255));
        txtCargo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtCargo.setForeground(new java.awt.Color(0, 0, 0));
        txtCargo.setBorder(null);
        txtCargo.setMinimumSize(new java.awt.Dimension(1, 20));
        txtCargo.setPreferredSize(new java.awt.Dimension(1, 20));
        add(txtCargo);
        txtCargo.setBounds(310, 40, 330, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblCodigoMarcacion;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCodigoMarcacion;
    // End of variables declaration//GEN-END:variables
}
