package com.prgmtc.keymatrix.vista.per;

public class pnEstudiante extends javax.swing.JPanel {

    /**
     * Creates new form pnEstudiante
     */
    public pnEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRu = new javax.swing.JLabel();
        txtRu = new javax.swing.JTextField();
        lblFechaIng = new javax.swing.JLabel();
        txtFechaIng = new com.toedter.calendar.JDateChooser();
        lblTipo = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(102, 102, 102));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(720, 120));
        setLayout(null);

        lblRu.setBackground(new java.awt.Color(153, 153, 153));
        lblRu.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblRu.setForeground(new java.awt.Color(0, 0, 0));
        lblRu.setText("R.U.");
        add(lblRu);
        lblRu.setBounds(10, 40, 40, 30);

        txtRu.setBackground(new java.awt.Color(255, 255, 255));
        txtRu.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        txtRu.setForeground(new java.awt.Color(0, 0, 0));
        txtRu.setBorder(null);
        txtRu.setMinimumSize(new java.awt.Dimension(1, 20));
        txtRu.setPreferredSize(new java.awt.Dimension(1, 20));
        add(txtRu);
        txtRu.setBounds(50, 40, 90, 30);

        lblFechaIng.setBackground(new java.awt.Color(153, 153, 153));
        lblFechaIng.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblFechaIng.setForeground(new java.awt.Color(0, 0, 0));
        lblFechaIng.setText("Fecha Ingreso");
        add(lblFechaIng);
        lblFechaIng.setBounds(160, 40, 120, 30);

        txtFechaIng.setBackground(new java.awt.Color(255, 255, 255));
        txtFechaIng.setForeground(new java.awt.Color(0, 0, 0));
        txtFechaIng.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        add(txtFechaIng);
        txtFechaIng.setBounds(283, 40, 160, 28);

        lblTipo.setBackground(new java.awt.Color(153, 153, 153));
        lblTipo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTipo.setForeground(new java.awt.Color(0, 0, 0));
        lblTipo.setText("Tipo");
        add(lblTipo);
        lblTipo.setBounds(470, 40, 60, 30);

        cmbTipo.setBackground(new java.awt.Color(255, 255, 255));
        cmbTipo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        cmbTipo.setForeground(new java.awt.Color(0, 0, 0));
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beca Completa\t", "Media Beca", "Sin Beca" }));
        cmbTipo.setSelectedIndex(2);
        add(cmbTipo);
        cmbTipo.setBounds(520, 40, 170, 27);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel lblFechaIng;
    private javax.swing.JLabel lblRu;
    private javax.swing.JLabel lblTipo;
    private com.toedter.calendar.JDateChooser txtFechaIng;
    private javax.swing.JTextField txtRu;
    // End of variables declaration//GEN-END:variables
}
