package com.prgmtc.keymatrix.vista;

import com.prgmtc.keymatrix.modelo.Docente;
import com.prgmtc.keymatrix.modelo.Docente_materia;
import com.prgmtc.keymatrix.modelo.Persona;
import com.prgmtc.keymatrix.modelo.PersonaDAO;
import java.util.List;

/**
 *
 * @author eanav
 */
public class frmDocenteA extends javax.swing.JFrame {
private int idpersona;
    /**
     * Creates new form frmDocenteA
     */
    public frmDocenteA(int idPersona) {
        this.idpersona = idPersona;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(900,540);
        
        Docente dc = new Docente();
        dc.Cargar(this.idpersona);
        Persona pn = new Persona();
        PersonaDAO pnd = new PersonaDAO();
        pn = pnd.cargar(idPersona);
        Docente_materia dmt = new Docente_materia();
        List<Docente_materia> ldmt = null;
        ldmt = dmt.Materias_docente(idPersona);
        
        this.lblNombreDocente.setText(pn.getNombres() + " " + pn.getApellidos());
        
        this.txtCod1.setText(String.valueOf(ldmt.get(0).getIdDocente_materia()));
        this.txtSemestre1.setText(ldmt.get(0).getSemestre());
        this.txtSigla1.setText(ldmt.get(0).getSigla());
        this.txtMateria1.setText(ldmt.get(0).getNombre_materia());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDocente = new javax.swing.JLabel();
        lblNombreDocente = new javax.swing.JLabel();
        lblDocente1 = new javax.swing.JLabel();
        txtCod1 = new javax.swing.JTextField();
        txtSemestre1 = new javax.swing.JTextField();
        txtMateria1 = new javax.swing.JTextField();
        txtSigla1 = new javax.swing.JTextField();
        chkMateria1 = new javax.swing.JCheckBox();
        txtCod2 = new javax.swing.JTextField();
        txtSemestre2 = new javax.swing.JTextField();
        txtSigla2 = new javax.swing.JTextField();
        txtMateria2 = new javax.swing.JTextField();
        chkMateria2 = new javax.swing.JCheckBox();
        btnAlmacenar = new javax.swing.JPanel();
        lblBtnAlmacenar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(800, 540));
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 213, 245));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Solicitud de Aulas Para Docentes");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(280, 60, 410, 30);

        lblDocente.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblDocente.setText("Materias:");
        getContentPane().add(lblDocente);
        lblDocente.setBounds(30, 200, 130, 40);

        lblNombreDocente.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lblNombreDocente.setText("jLabel1");
        getContentPane().add(lblNombreDocente);
        lblNombreDocente.setBounds(190, 130, 450, 40);

        lblDocente1.setFont(new java.awt.Font("Roboto Light", 1, 24)); // NOI18N
        lblDocente1.setText("Docente:");
        getContentPane().add(lblDocente1);
        lblDocente1.setBounds(30, 130, 130, 40);

        txtCod1.setBackground(new java.awt.Color(255, 255, 255));
        txtCod1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtCod1.setBorder(null);
        getContentPane().add(txtCod1);
        txtCod1.setBounds(150, 244, 100, 50);

        txtSemestre1.setBackground(new java.awt.Color(255, 255, 255));
        txtSemestre1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtSemestre1.setBorder(null);
        txtSemestre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSemestre1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSemestre1);
        txtSemestre1.setBounds(260, 244, 130, 50);

        txtMateria1.setBackground(new java.awt.Color(255, 255, 255));
        txtMateria1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtMateria1.setBorder(null);
        getContentPane().add(txtMateria1);
        txtMateria1.setBounds(520, 244, 240, 50);

        txtSigla1.setBackground(new java.awt.Color(255, 255, 255));
        txtSigla1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtSigla1.setBorder(null);
        getContentPane().add(txtSigla1);
        txtSigla1.setBounds(400, 244, 110, 50);

        chkMateria1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        chkMateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMateria1ActionPerformed(evt);
            }
        });
        getContentPane().add(chkMateria1);
        chkMateria1.setBounds(770, 270, 40, 20);

        txtCod2.setBackground(new java.awt.Color(255, 255, 255));
        txtCod2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtCod2.setBorder(null);
        getContentPane().add(txtCod2);
        txtCod2.setBounds(150, 300, 100, 50);

        txtSemestre2.setBackground(new java.awt.Color(255, 255, 255));
        txtSemestre2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtSemestre2.setBorder(null);
        txtSemestre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSemestre2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtSemestre2);
        txtSemestre2.setBounds(260, 300, 130, 50);

        txtSigla2.setBackground(new java.awt.Color(255, 255, 255));
        txtSigla2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtSigla2.setBorder(null);
        getContentPane().add(txtSigla2);
        txtSigla2.setBounds(400, 300, 110, 50);

        txtMateria2.setBackground(new java.awt.Color(255, 255, 255));
        txtMateria2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        txtMateria2.setBorder(null);
        getContentPane().add(txtMateria2);
        txtMateria2.setBounds(520, 300, 240, 50);

        chkMateria2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        chkMateria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMateria2ActionPerformed(evt);
            }
        });
        getContentPane().add(chkMateria2);
        chkMateria2.setBounds(770, 330, 40, 20);

        btnAlmacenar.setBackground(new java.awt.Color(0, 213, 245));
        btnAlmacenar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlmacenarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlmacenarMouseExited(evt);
            }
        });
        btnAlmacenar.setLayout(null);

        lblBtnAlmacenar.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblBtnAlmacenar.setForeground(new java.awt.Color(3, 7, 71));
        lblBtnAlmacenar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBtnAlmacenar.setText("Almacenar");
        lblBtnAlmacenar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlmacenar.add(lblBtnAlmacenar);
        lblBtnAlmacenar.setBounds(0, 0, 200, 50);

        getContentPane().add(btnAlmacenar);
        btnAlmacenar.setBounds(590, 420, 200, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSemestre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemestre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemestre1ActionPerformed

    private void chkMateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMateria1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMateria1ActionPerformed

    private void txtSemestre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSemestre2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSemestre2ActionPerformed

    private void chkMateria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMateria2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkMateria2ActionPerformed

    private void btnAlmacenarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlmacenarMouseEntered
        // TODO add your handling code here:
        btnAlmacenar.setBackground(new java.awt.Color(255,153,0));
        lblBtnAlmacenar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnAlmacenarMouseEntered

    private void btnAlmacenarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlmacenarMouseExited
        // TODO add your handling code here:
        btnAlmacenar.setBackground(new java.awt.Color(0, 213, 245));
        lblBtnAlmacenar.setForeground(new java.awt.Color(3, 7, 71));
    }//GEN-LAST:event_btnAlmacenarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnAlmacenar;
    private javax.swing.JCheckBox chkMateria1;
    private javax.swing.JCheckBox chkMateria2;
    private javax.swing.JLabel lblBtnAlmacenar;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblDocente1;
    private javax.swing.JLabel lblNombreDocente;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCod1;
    private javax.swing.JTextField txtCod2;
    private javax.swing.JTextField txtMateria1;
    private javax.swing.JTextField txtMateria2;
    private javax.swing.JTextField txtSemestre1;
    private javax.swing.JTextField txtSemestre2;
    private javax.swing.JTextField txtSigla1;
    private javax.swing.JTextField txtSigla2;
    // End of variables declaration//GEN-END:variables
}
