
package com.prgmtc.keymatrix.vista;

/**
 *
 * @author Elvis
 */

import com.prgmtc.keymatrix.modelo.UsuarioDAO;
import com.prgmtc.keymatrix.modelo.Usuario;
import java.util.Arrays;
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        lblClave = new javax.swing.JLabel();
        btnSalir = new javax.swing.JPanel();
        lblSalir = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtClave = new javax.swing.JPasswordField();
        btnEnter = new javax.swing.JPanel();
        lblEnter = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("frmLogin"); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        bg.setBackground(new java.awt.Color(204, 204, 204));
        bg.setAutoscrolls(true);
        bg.setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Iniciar Sesión");
        bg.add(lblTitulo);
        lblTitulo.setBounds(340, 30, 260, 60);

        lblUsuario.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(4, 248, 255));
        lblUsuario.setText("Usuario");
        bg.add(lblUsuario);
        lblUsuario.setBounds(340, 130, 260, 60);

        lblClave.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblClave.setForeground(new java.awt.Color(4, 248, 255));
        lblClave.setText("Clave");
        bg.add(lblClave);
        lblClave.setBounds(340, 220, 260, 60);

        btnSalir.setBackground(new java.awt.Color(255, 204, 0));
        btnSalir.setForeground(new java.awt.Color(1, 18, 38));
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
        });

        lblSalir.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(1, 18, 38));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setText("X");
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirLayout = new javax.swing.GroupLayout(btnSalir);
        btnSalir.setLayout(btnSalirLayout);
        btnSalirLayout.setHorizontalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );
        btnSalirLayout.setVerticalGroup(
            btnSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSalirLayout.createSequentialGroup()
                .addComponent(lblSalir)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        bg.add(btnSalir);
        btnSalir.setBounds(670, 0, 30, 30);

        txtUsuario.setBackground(new java.awt.Color(4, 84, 175));
        txtUsuario.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario.setBorder(null);
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        bg.add(txtUsuario);
        txtUsuario.setBounds(340, 170, 240, 30);

        txtClave.setBackground(new java.awt.Color(4, 84, 175));
        txtClave.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        txtClave.setForeground(new java.awt.Color(255, 255, 255));
        txtClave.setBorder(null);
        bg.add(txtClave);
        txtClave.setBounds(340, 260, 240, 30);

        btnEnter.setBackground(new java.awt.Color(4, 84, 175));
        btnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnterMouseClicked(evt);
            }
        });

        lblEnter.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblEnter.setForeground(new java.awt.Color(4, 248, 255));
        lblEnter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEnter.setText("Entrar");
        lblEnter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(4, 248, 255)));
        lblEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEnterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblEnterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblEnterMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnEnterLayout = new javax.swing.GroupLayout(btnEnter);
        btnEnter.setLayout(btnEnterLayout);
        btnEnterLayout.setHorizontalGroup(
            btnEnterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEnter, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        btnEnterLayout.setVerticalGroup(
            btnEnterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEnter, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        bg.add(btnEnter);
        btnEnter.setBounds(340, 320, 160, 40);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgLogin.png"))); // NOI18N
        lblFondo.setText("jLabel2");
        bg.add(lblFondo);
        lblFondo.setBounds(0, 0, 700, 400);

        getContentPane().add(bg);
        bg.setBounds(0, 0, 700, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        // TODO add your handling code her
    }//GEN-LAST:event_btnSalirMouseEntered

    private void lblSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseEntered
        // TODO add your handling code here:
        btnSalir.setBackground(new java.awt.Color(1,18,38));
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_lblSalirMouseEntered

    private void lblSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseExited
        // TODO add your handling code here:
        btnSalir.setBackground(new java.awt.Color(255,204,0));
        btnSalir.setForeground(new java.awt.Color(1,18,38));
    }//GEN-LAST:event_lblSalirMouseExited

    private void lblEnterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnterMouseEntered
        // TODO add your handling code here:
        btnEnter.setBackground(new java.awt.Color(1,18,38));
        lblEnter.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_lblEnterMouseEntered

    private void lblEnterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnterMouseExited
        // TODO add your handling code here:
        btnEnter.setBackground(new java.awt.Color(4, 84, 175));
        lblEnter.setForeground(new java.awt.Color(4, 248, 255));
    }//GEN-LAST:event_lblEnterMouseExited

    private void lblEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEnterMouseClicked
        // TODO add your handling code here:
        if ((txtUsuario.getText().length() <= 1) || (txtClave.getPassword().length <= 1)) {
            javax.swing.JOptionPane.showMessageDialog(null, "Ambos Campos son necesarios :(", 
                    "Advertencia", javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            UsuarioDAO usd = new UsuarioDAO();
            if ( usd.valida(txtUsuario.getText(), txtClave.getText()))
            {
                
                this.setVisible(false);
                this.dispose();
                
                frmPersona fp = new frmPersona();
                fp.setVisible(true);
                
                
            }
        }
        

        
        
    }//GEN-LAST:event_lblEnterMouseClicked

    private void btnEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseClicked
        // TODO add your handling code here:
                    
        
    }//GEN-LAST:event_btnEnterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel btnEnter;
    private javax.swing.JPanel btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblEnter;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtClave;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
